@port = 3000
@endpoint = http://localhost:{{port}}/api/v1/users

POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Admin",
  "phone": "0870000000",
  "email": "test.user@admin.atu.ie",
  "dob": "1995-05-15",
  "role": "admin",
  "password": "password123"
}