@port = 3000
@endpoint = http://localhost:{{port}}/api/v1/users

###
### POST Request for a user
## Expected result is ........
# @name postAUser
POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Garry Ledwith",
  "phonenumber": "0879865432",
  "email": "garryledwith@gmail.com",
  "dob": "1990-01-01",
  "role": "student",
  "dateJoined": "2023-10-01",
  "lastUpdated": "2023-10-01"
}

